### ISSUE TITLE
Add ability to refresh manifest file on each request.

### ISSUE THREAD

**Issue by yoihito** [auchenberg/express-webpack-asset#1]
It seems me cool to add this ability for development mode. I have set up development environment with the bunch of things, like express.js, nodemon, webpack and webpack-middleware. Webpack-middleware   watches for changes in assets and rebuilds them. That is why their hashes are updating too. But express-webpack-asset loader still uses old manifest file. So it would be nice to reload manifest file.

**Comment by owais** [comment]
@yoihito I've submitted a simple PR to fix this. #2

**Comment by auchenberg** [comment]
Fixed in https://github.com/auchenberg/express-webpack-asset/commit/64eefb7464457ae990b96ce595a40d7a6f5722bd
